In [1]:
import numpy as np
vize=[10,20,30,40]
final=[2,60,32,50]

vize_np=np.array(vize)
final_np=np.array(final)

ortalama=(vize_np+final_np)/2
print(ortalama)

[ 6. 40. 31. 45.]


In [2]:
import numpy as np


my_array=np.array([[1,2,3],[4,5,6]])

print(my_array)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

my_array=np.array([[1,2,3,],[4,5,6],[7,8,9]])


print(my_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8])
max_value=np.amax(arr)
print(max_value)

8


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
max_value=np.amax(arr)
print(max_value)

8


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
max_values=np.amax(arr,axis=1)
print(max_values)



[ 4  8 12]


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
max_values=np.amax(arr,axis=0)
print(max_values)

[ 9 10 11 12]


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
max_values=np.amax(arr,axis=1, keepdims=True)
print(max_values)

[[ 4]
 [ 8]
 [12]]


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
max_value=np.amax(arr,initial=0)
print(max_value)



8


In [11]:
import pandas as pd
my_list=[1,2,3,4,5]
my_series=pd.Series(my_list)
print(my_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [12]:
import pandas as pd
my_dict={'name':['elif','mustafa','zehra','beyza'], 'age':[34,38,7,4]}
my_dataframe=pd.DataFrame(my_dict)
print(my_dataframe)

      name  age
0     elif   34
1  mustafa   38
2    zehra    7
3    beyza    4
